package config

var DISCORD_BOT_TOKEN = ""
var DISCORD_ADMIN_USERNAMES_STRING = ""
var DISCORD_ADMIN_USERNAMES = []string{}
var DISCORD_COMMAND_PREFIX = "!palbot"
var PALWORLD_RCON_HOST = "127.0.0.1"
var PALWORLD_RCON_PORT_STRING = "25575"
var PALWORLD_RCON_PORT uint64 = 25575
var PALWORLD_RCON_PASSWORD = ""
var DISCORD_DASHBOARD_CHANNEL_ID = ""
var DISCORD_DASHBAORD_ONLINE_PLAYERS_MESSAGE_ID = ""
var DISCORD_LOG_CHANNEL_ID = ""
var LANGUAGE = "en"
