package config

var DISCORD_BOT_TOKEN = ""
var DISCORD_ADMIN_USERNAMES_STRING = ""
var DISCORD_ADMIN_USERNAMES = []string{}
var DISCORD_COMMAND_PREFIX = "!palbot"
var PALWORLD_RCON_HOST = ""
var PALWORLD_RCON_PORT = ""
var PALWORLD_RCON_PASSWORD = ""
