package config

import (
	"fmt"
	"os"
	"strings"
)

func Save() error {
	env := strings.TrimSpace(
		fmt.Sprintf(`
DISCORD_BOT_TOKEN=%s
DISCORD_ADMIN_USERNAMES=%s
DISCORD_COMMAND_PREFIX=%s

PALWORLD_RCON_HOST=%s
PALWORLD_RCON_PORT=%d
PALWORLD_ADMIN_PASSWORD=%s
PALWORLD_SERVER_PATH=%s

DISCORD_DASHBOARD_CHANNEL_ID=%s
DISCORD_LOG_CHANNEL_ID=%s
DISCORD_DASHBOARD_PALWORLD_CONFIG_MESSAGE_ID=%s
DISCORD_DASHBOARD_ONLINE_PLAYERS_MESSAGE_ID=%s

LANGUAGE=%s
`,
			DISCORD_BOT_TOKEN,
			strings.Join(DISCORD_ADMIN_USERNAMES, ","),
			DISCORD_COMMAND_PREFIX,

			PALWORLD_RCON_HOST,
			PALWORLD_RCON_PORT,
			PALWORLD_ADMIN_PASSWORD,
			PALWORLD_SERVER_PATH,

			DISCORD_DASHBOARD_CHANNEL_ID,
			DISCORD_LOG_CHANNEL_ID,
			DISCORD_DASHBOARD_PALWORLD_CONFIG_MESSAGE_ID,
			DISCORD_DASHBOARD_ONLINE_PLAYERS_MESSAGE_ID,

			LANGUAGE,
		),
	)

	return os.WriteFile(".env", []byte(env), 0644)
}
