name: Add release assets

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - run: sh build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: release-assets
          path: ./out

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./out/*
